### ISSUE TITLE
Introduction page for v20 server

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#123]
## Key features
- Event streams
- Real-time subscriptions
- Server-side filtering
- High availability
- gRPC
- Persistent subscriptions
- Server-side projections

## Cloud

Shall we include Cloud to this page?

**Comment by dharmaturtle** [comment]
I want to add the results of [this conversation](https://github.com/EventStore/EventStore/issues/2639) to the [getting started page](https://developers.eventstore.com/server/20.6/server/introduction/#getting-started), but that seems currently inappropriate. Should we rename that page "Introduction", or delete it entirely? (I'm not entirely convinced it has value.)

I want to add a "real" "Getting started" page that's more akin to the 5.x docs. Also should be documented somewhere that the admin portal on 2113 is intentionally not enabling some tabs due to security stuff.

**Comment by alexeyzimarev** [comment]
@dharmaturtle for the server v20 the intro page is there. What exactly would you include there, considering the current state of the docs?

**Comment by oskardudycz** [comment]
Currently, we have already such page https://www.eventstore.com/eventstoredb. @alexeyzimarev @mat-mcloughlin if you think that we should enhance that then feel free to reopen the issue.
