### ISSUE TITLE
.Net API - Missing Topics

### ISSUE THREAD

**Issue by rcknight** [EventStore/documentation#28]
- [x] Subscriptions aren't documented at all?!?!
- [x] Authentication is never mentioned
  (I've now added this to the connecting to a server page, but it should be mentioned on the reading streams etc as well)
- [x] Cluster settings (this might be in server docs? should at least link to that)
- [x] Connection events (mentioned as part of connectionsettings, but they aren't there anymore)
- [x] Getting/Setting metadata
- [x] EventData + ResolvedEvent not mentioned - seems like we had docs on these once, but dead links now?
- [x] ReadEvent (single)
- [ ] SetSystemSettings - Is this new in 3.0.1? I don't even know what this does??
- [x] Reading from the all stream
- [x] Deleting Streams

**Comment by haf** [comment]
Persistent subscriptions https://github.com/EventStore/EventStore/blob/dev/etc/EventStore.CompetingPlayground/Program.cs - had to browse the source **too much** to find reference to these classes.

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/docs.geteventstore.com/pull/68/files

On Tuesday, January 20, 2015, Henrik Feldt <notifications@github.com> wrote:

> Persistent subscriptions
> https://github.com/EventStore/EventStore/blob/dev/etc/EventStore.CompetingPlayground/Program.cs
> - had to browse the source *too much* to find reference to these classes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-70730438>
> .
>


-- 
Studying for the Turing test

**Comment by haf** [comment]
Let's say I create a CatchUp subscription for the stream `$ce-monkeyworks` -- how do I get the 'currently consumed position' from there?

**Comment by gregoryyoung** [comment]
A catch up subscription you keep it yourself. It's the position you pass to
the subscription and gets passed to you. It's a client state based
subscription. A persistent subscription the server holds the state.

On Tuesday, January 20, 2015, Henrik Feldt <notifications@github.com> wrote:

> Let's say I create a CatchUp subscription for the stream $ce-monkeyworks
> -- how do I get the 'currently consumed position' from there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-70732286>
> .
>


-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Btw note the version on the docs. This is part of why it's not so simple as
"just release your bug fix" there is a significant amount of other things
in that release including competting consumers.

On Tuesday, January 20, 2015, Greg Young <gregoryyoung1@gmail.com> wrote:

> https://github.com/EventStore/docs.geteventstore.com/pull/68/files
>
> On Tuesday, January 20, 2015, Henrik Feldt <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Persistent subscriptions
>> https://github.com/EventStore/EventStore/blob/dev/etc/EventStore.CompetingPlayground/Program.cs
>> - had to browse the source *too much* to find reference to these classes.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-70730438>
>> .
>>
>
>
> --
> Studying for the Turing test
>
>

-- 
Studying for the Turing test

**Comment by haf** [comment]
About the catch-up subscription: exactly, but what API to get the number from?

![screen shot 2015-01-20 at 22 04 27](https://cloud.githubusercontent.com/assets/193115/5826081/540b21c6-a0f0-11e4-8b26-2d7453355000.png)

That's the original, so is the `Event.EventNumber`.

Not on the subscription

![screen shot 2015-01-20 at 22 06 39](https://cloud.githubusercontent.com/assets/193115/5826120/a40ee4b4-a0f0-11e4-9ac3-0b26cd0dd0aa.png)

Here's one:

![screen shot 2015-01-20 at 22 07 44](https://cloud.githubusercontent.com/assets/193115/5826140/c9882a7a-a0f0-11e4-9bad-bc64ec1ca7b0.png)

But am I supposed to poll that and join its update with a successful handle of an event from the subscriber?

**Comment by gregoryyoung** [comment]
Depends whether you are subscribed to all or to a stream (there are two
catchupsubscriptions).

All  e.OriginalPosition
Stream e.OriginalEventNumber

The reason why you want original event number is it could be a link event
(you want the number of the link not of the resolved event)

On Tue, Jan 20, 2015 at 11:08 PM, Henrik Feldt <notifications@github.com>
wrote:

> About the catch-up subscription: exactly, but what API to get the number
> from?
>
> [image: screen shot 2015-01-20 at 22 04 27]
> <https://cloud.githubusercontent.com/assets/193115/5826081/540b21c6-a0f0-11e4-8b26-2d7453355000.png>
>
> That's the original, so is the Event.EventNumber.
>
> Not on the subscription
>
> [image: screen shot 2015-01-20 at 22 06 39]
> <https://cloud.githubusercontent.com/assets/193115/5826120/a40ee4b4-a0f0-11e4-9ac3-0b26cd0dd0aa.png>
>
> Here's one:
>
> [image: screen shot 2015-01-20 at 22 07 44]
> <https://cloud.githubusercontent.com/assets/193115/5826140/c9882a7a-a0f0-11e4-9bad-bc64ec1ca7b0.png>
>
> But am I supposed to poll that and join its update with a successful
> handle of an event from the subscriber?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-70733753>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
If I'm, like in this case, subscribed to a derivative stream, $ce-monkeyworks, I'm going to get events from all different sorts of streams on that subscription: is there a position for `$ce-monkeyworks`?

**Comment by gregoryyoung** [comment]
Yes thats why you use Original ... It is the case I mentioned with linked
events. You will get the original and the linked event (providing you have
set resolve flag)

On Tue, Jan 20, 2015 at 11:19 PM, Henrik Feldt <notifications@github.com>
wrote:

> If I'm, like in this case, subscribed to a derivative stream,
> $ce-monkeyworks, I'm going to get events from all different sorts of
> streams on that subscription: is there a position for $ce-monkeyworks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-70735619>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
I was thinking about the version and 'release a fix' that I keep saying, now that I'm instrumenting another unit test project with the hard-to-use embedded server.

You're right that it's not that simple right now, due to the way you've done releases for this project, but it's very doable. You can either choose to backport fixes (pretty annoying work), or you can keep a might higher release cadence. It's not like this is news to the software industry ;) - I've worked at places where it was my sole mission to make releases more frequent - it's after all the best way to minimise risk. Therefore, having pre-releases should not be a big problem - after all, it's not like you've kept the docs up to date with the current old releases either, so it can't be that that stops you (unless you've very recently decided to make full docs a requirement for a release).

Anyway, you're doing good work and I really appreciate the direct line of communication as well as you being mostly responsive - but I'm not going to agree that just having a "significant amount of other things" will inevitably stop you from releasing often.

**Comment by gregoryyoung** [comment]
after all, it's not like you've kept the docs up to date with the current
old releases either, so it can't be that that stops you (unless you've very
recently decided to make full docs a requirement for a release).

Perhaps that's correlated with the hundred or so commits to docs over the
last 6 weeks or so?

On Thursday, January 22, 2015, Henrik Feldt <notifications@github.com>
wrote:

> I was thinking about the version and 'release a fix' that I keep saying,
> now that I'm instrumenting another unit test project with the hard-to-use
> embedded server.
>
> You're right that it's not that simple right now, due to the way you've
> done releases for this project, but it's very doable. You can either choose
> to backport fixes (pretty annoying work), or you can keep a might higher
> release cadence. It's not like this is news to the software industry ;) -
> I've worked at places where it was my sole mission to make releases more
> frequent - it's after all the best way to minimise risk. Therefore, having
> pre-releases should not be a big problem - after all, it's not like you've
> kept the docs up to date with the current old releases either, so it can't
> be that that stops you (unless you've very recently decided to make full
> docs a requirement for a release).
>
> Anyway, you're doing good work and I really appreciate the direct line of
> communication as well as you being mostly responsive - but I'm not going to
> agree that just having a "significant amount of other things" will
> inevitably stop you from releasing often.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-71034421>
> .
>


-- 
Studying for the Turing test

**Comment by jen20** [comment]
@haf Since we actually care about things being durable (for example), we like to actually test features we have to support indefinitely before we release them. Infrastructure isn't a rails app - you don't just fire shit to production and hope it works.

Part of the benefit of being open source and liberally licensed is that you *can* build yourself. It's not hard, the build scripts work on almost every machine you'll find, and if you meet the (minimal) dependencies and it doesn't work then file it as an issue. Blessed binaries mean nothing unless you're paying for commercial support anyway.

**Comment by haf** [comment]
@gregoryyoung Yes, that would explain it. Seems like we're in agreement then! I'm not saying *this is bad*, necessarily, I'm just saying it's the case.

@jen20 You wouldn't have to support pre-releases if you say you don't support them. For me, as a consumer of your work, going with the pre-release is a hedge against future pain - it

  1) allows me to test what you're doing and help/interact with you during the development process,
  2) allows me to use the infrastructure that all of .Net/(Core) is migrating to - packages instead of compiled artifacts in `lib` folders. So in fact, pre-release from this project would likely end up in test environments instead of in production.

I don't understand why you call that to *fire shit into production*? It's a normal part of working with software and doing it doesn't take away anything from your stable release.

It's also a matter of coupling - the name of your package becomes highly coupled to the consumers - so if I would build myself and publish nuget `EventStore-Latest` - I would have to change all places and all consumers of that nuget - not to mention consumers of consumers -- something that adds to my workload as an open source developer. Namely these, at this point:

 - logary event store adapter
 - eventstore.client.fsharp

Logary takes 20 minutes to make a release of (compile time plus upload time) and 5 minutes to modify, and the client takes about 3 + 5 minutes; that's already a good part of a day - half an hour. Not to mention release notes and misc handling, each 5 minutes - about 40 minutes in total - even if you've just added a single method to the binary.

Not only that, but I would have to modify your build scripts to build nugets. I would also have to host a downloadable binary somewhere, like on github. This takes time and I'd have to rebase-merge every time you change your build script, which can take all from 30 seconds to 20 minutes, depending on the breakage. That's another overhead.

Add all of this to the fact that I'm trying to write commercial software AND keep about 20 other nugets maintained, you soon realise that what I'm asking for - make your CI server push a prerelease on compile - is not that much to ask for.

**Comment by jen20** [comment]
What kind of interval would these prereleases get pushed on? When there's active feature work being done there are 30-40 compiles a day - I assume you wouldn't want every one of them going to NuGet? What about the server? What about branches with completely new partially implemented features that haven't yet undergone serious testing?

The build scripts don't build NuGets by default as we have no use for them - the scripts are in fact there though (see `scripts/nuget-clientapi/package-clientapi.ps1`).

For now we'll err on the side of caution with this and not release pre-release binaries, and certainly not prerelease NuGets. If they end up in production and someone loses data because of it, it will come back to bite us in the ass. It will definitely happen, too (see the continuing saga of the "unsafe-disable-flush-to-disk" flag).

**Comment by gregoryyoung** [comment]
There is also something to be said for the barrier to entry of building in
terms of filtering who is actually using it bleeding edge.

On Thursday, January 22, 2015, James Nugent <notifications@github.com>
wrote:

> What kind of interval would these prereleases get pushed on? When there's
> active feature work being done there are 30-40 compiles a day - I assume
> you wouldn't want every one of them going to NuGet? What about the server?
> What about branches with completely new partially implemented features that
> haven't yet undergone serious testing?
>
> The build scripts don't build NuGets by default as we have no use for them
> - the scripts are in fact there though (see
> scripts/nuget-clientapi/package-clientapi.ps1).
>
> For now we'll err on the side of caution with this and not release
> pre-release binaries, and certainly not prerelease NuGets. If they end up
> in production and someone loses data because of it, it will come back to
> bite us in the ass. It will definitely happen, too (see the continuing saga
> of the "unsafe-disable-flush-to-disk" flag).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/28#issuecomment-71041547>
> .
>


-- 
Studying for the Turing test

**Comment by haf** [comment]
What kind of interval? One per day or one per week would be fine - just configure a scheduled build in your CI server - done. This is a really annoying problem when there are months - or even in ES' case *years* between releases.

What about the server? A corresponding chain-build of the server pushed to the Releases page on github (not on the official site if you don't want).

Only build one branch - `dev` seems to be the name of choice. Don't build feature branches to nugets.

Display prominent warnings that it's automated builds and no hands-on testing except the default range of automated tests have been run.

Since you have an awesome test setup from photos and talks - use the week up to the pre-release push to run those tests -- if the CI server crashes in between - well, then we'll see the pre-release the next week and that's fine too.

**Comment by ChrisChinchilla** [comment]
As far as I can tell, `SetSystemSettings` is the implicit bunch of settings people can create when they create a connection and also change. Thus I think this issue can be closed.
