### ISSUE TITLE
Why OptimizeIndexMerge is false by default

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#98]
> OptimizeIndexMerge allows faster merging of indexes when Event Store has scavenged a chunk. 

The question is why is it `false` by default?

**Comment by mat-mcloughlin** [comment]
@pgermishuys @hayley-jean don't suppose you know the answer for this?

**Comment by pgermishuys** [comment]
Unfortunately I don't as this was added when I wasn't around. I suspect the reason is just general caution.
@shaan1337 might be able to shed some light.

**Comment by mat-mcloughlin** [comment]
@jageall can you shed any light on this?

**Comment by mat-mcloughlin** [comment]
Feedback from Shaan

**Mat**  @here Got an outstanding issue in docs. Wondering if anybody knows why optimise index merge setting on the server is set to false by default?
**hayleyjean**  I think it was just because it was a new option. @shaan is it safe to enable by default?
**shaan**  yup, it was an experimental option @hayleyjean i don't think we have many customers using it right now, so we may not have enough data to confirm if it's safe to enable by default
**shaan**  given that the index system is going to change completely soon, it would be better to keep it off IMO

**Comment by mat-mcloughlin** [comment]
@hayley-jean we are just chasing up on some outstanding issues. Is this something you'd want to consider turning on by default now?
